'use client';

import { useState, useEffect } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Leaf, Target, TrendingUp, Award, Globe, Users, Zap, Recycle, Heart, Shield } from 'lucide-react';
import { toast } from 'sonner';

type SDGGoal = {
  id: number;
  title: string;
  description: string;
  icon: string;
  color: string;
  progress: number;
  relevance: number;
};

type ImpactMetric = {
  category: string;
  value: number;
  unit: string;
  trend: 'up' | 'down' | 'stable';
  description: string;
  icon: React.ReactNode;
};

type ProjectImpact = {
  id: string;
  name: string;
  sdgAlignment: number[];
  carbonFootprint: number;
  usersImpacted: number;
  ethicalScore: number;
  sustainabilityRating: 'A' | 'B' | 'C' | 'D';
  impactAreas: string[];
};

const SDG_GOALS: SDGGoal[] = [
  {
    id: 1,
    title: "No Poverty",
    description: "End poverty in all its forms everywhere",
    icon: "🏠",
    color: "bg-red-500",
    progress: 65,
    relevance: 85
  },
  {
    id: 3,
    title: "Good Health and Well-being",
    description: "Ensure healthy lives and promote well-being for all",
    icon: "❤️",
    color: "bg-green-500",
    progress: 78,
    relevance: 92
  },
  {
    id: 4,
    title: "Quality Education",
    description: "Ensure inclusive and equitable quality education",
    icon: "📚",
    color: "bg-blue-500",
    progress: 72,
    relevance: 88
  },
  {
    id: 8,
    title: "Decent Work and Economic Growth",
    description: "Promote sustained, inclusive economic growth",
    icon: "💼",
    color: "bg-purple-500",
    progress: 68,
    relevance: 75
  },
  {
    id: 9,
    title: "Industry, Innovation and Infrastructure",
    description: "Build resilient infrastructure, promote innovation",
    icon: "🏭",
    color: "bg-orange-500",
    progress: 82,
    relevance: 95
  },
  {
    id: 13,
    title: "Climate Action",
    description: "Take urgent action to combat climate change",
    icon: "🌍",
    color: "bg-emerald-500",
    progress: 45,
    relevance: 90
  }
];

const IMPACT_METRICS: ImpactMetric[] = [
  {
    category: "Environmental",
    value: 2.4,
    unit: "tons CO₂ saved",
    trend: "up",
    description: "Carbon footprint reduction through digital solutions",
    icon: <Leaf className="h-5 w-5" />
  },
  {
    category: "Social",
    value: 15000,
    unit: "people reached",
    trend: "up",
    description: "Direct beneficiaries of hackathon projects",
    icon: <Users className="h-5 w-5" />
  },
  {
    category: "Economic",
    value: 850000,
    unit: "USD value created",
    trend: "up",
    description: "Economic value generated by projects",
    icon: <TrendingUp className="h-5 w-5" />
  },
  {
    category: "Innovation",
    value: 95,
    unit: "% ethical compliance",
    trend: "stable",
    description: "AI ethics and responsible innovation score",
    icon: <Shield className="h-5 w-5" />
  }
];

export default function ImpactTracker() {
  const [selectedProject, setSelectedProject] = useState<string>('');
  const [impactData, setImpactData] = useState<ProjectImpact | null>(null);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [blockchainVerified, setBlockchainVerified] = useState(false);

  const analyzeProjectImpact = async (projectName: string) => {
    setIsAnalyzing(true);
    toast.success('Analyzing project impact...');

    // Simulate AI analysis
    setTimeout(() => {
      const mockImpact: ProjectImpact = {
        id: '1',
        name: projectName,
        sdgAlignment: [3, 4, 9, 13],
        carbonFootprint: -2.4,
        usersImpacted: 15000,
        ethicalScore: 95,
        sustainabilityRating: 'A',
        impactAreas: ['Healthcare', 'Education', 'Climate', 'Innovation']
      };

      setImpactData(mockImpact);
      setIsAnalyzing(false);
      toast.success('Impact analysis complete!');
    }, 3000);
  };

  const verifyOnBlockchain = () => {
    toast.success('Submitting to Algorand blockchain...');
    setTimeout(() => {
      setBlockchainVerified(true);
      toast.success('Impact metrics verified on blockchain!');
    }, 2000);
  };

  const getTrendIcon = (trend: 'up' | 'down' | 'stable') => {
    if (trend === 'up') return <TrendingUp className="h-4 w-4 text-green-500" />;
    if (trend === 'down') return <TrendingUp className="h-4 w-4 text-red-500 rotate-180" />;
    return <div className="h-4 w-4 bg-gray-400 rounded-full" />;
  };

  const getSustainabilityColor = (rating: string) => {
    const colors = {
      'A': 'bg-green-500',
      'B': 'bg-blue-500',
      'C': 'bg-yellow-500',
      'D': 'bg-red-500'
    };
    return colors[rating as keyof typeof colors] || 'bg-gray-500';
  };

  return (
    <div className="container mx-auto py-8 px-4">
      <div className="mb-8">
        <h1 className="text-3xl font-bold tracking-tight mb-2 flex items-center gap-2">
          <Target className="h-8 w-8 text-green-500" />
          Sustainability & Impact Tracker
        </h1>
        <p className="text-muted-foreground">
          Real-time assessment of your project's environmental and social impact
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Impact Metrics Overview */}
        <div className="lg:col-span-1">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Globe className="h-5 w-5" />
                Global Impact Metrics
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              {IMPACT_METRICS.map((metric, index) => (
                <div key={index} className="p-3 border rounded-lg">
                  <div className="flex items-center justify-between mb-2">
                    <div className="flex items-center gap-2">
                      {metric.icon}
                      <span className="font-medium text-sm">{metric.category}</span>
                    </div>
                    {getTrendIcon(metric.trend)}
                  </div>
                  <div className="space-y-1">
                    <p className="text-2xl font-bold">
                      {metric.value.toLocaleString()} <span className="text-sm font-normal">{metric.unit}</span>
                    </p>
                    <p className="text-xs text-muted-foreground">{metric.description}</p>
                  </div>
                </div>
              ))}

              <div className="pt-4 border-t">
                <Button 
                  onClick={verifyOnBlockchain}
                  disabled={blockchainVerified}
                  className="w-full"
                  variant={blockchainVerified ? "outline" : "default"}
                >
                  {blockchainVerified ? (
                    <>
                      <Award className="h-4 w-4 mr-2" />
                      Verified on Blockchain
                    </>
                  ) : (
                    'Verify on Algorand'
                  )}
                </Button>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Main Content */}
        <div className="lg:col-span-2">
          <Tabs defaultValue="analysis" className="space-y-4">
            <TabsList className="grid w-full grid-cols-3">
              <TabsTrigger value="analysis">Impact Analysis</TabsTrigger>
              <TabsTrigger value="sdg">SDG Alignment</TabsTrigger>
              <TabsTrigger value="ethics">Ethics & Compliance</TabsTrigger>
            </TabsList>

            <TabsContent value="analysis" className="space-y-4">
              <Card>
                <CardHeader>
                  <CardTitle>Project Impact Assessment</CardTitle>
                  <CardDescription>
                    AI-powered analysis of your project's sustainability impact
                  </CardDescription>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="flex gap-2">
                    <Select value={selectedProject} onValueChange={setSelectedProject}>
                      <SelectTrigger className="flex-1">
                        <SelectValue placeholder="Select a project to analyze" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="ai-healthcare">AI Healthcare Assistant</SelectItem>
                        <SelectItem value="climate-tracker">Climate Impact Tracker</SelectItem>
                        <SelectItem value="education-platform">Education Platform</SelectItem>
                        <SelectItem value="sustainable-transport">Sustainable Transport App</SelectItem>
                      </SelectContent>
                    </Select>
                    <Button 
                      onClick={() => analyzeProjectImpact(selectedProject)}
                      disabled={!selectedProject || isAnalyzing}
                    >
                      {isAnalyzing ? 'Analyzing...' : 'Analyze Impact'}
                    </Button>
                  </div>

                  {isAnalyzing && (
                    <div className="space-y-3">
                      <div className="space-y-2">
                        <div className="flex justify-between text-sm">
                          <span>Environmental impact calculation</span>
                          <span>75%</span>
                        </div>
                        <Progress value={75} />
                      </div>
                      <div className="space-y-2">
                        <div className="flex justify-between text-sm">
                          <span>Social benefit analysis</span>
                          <span>60%</span>
                        </div>
                        <Progress value={60} />
                      </div>
                      <div className="space-y-2">
                        <div className="flex justify-between text-sm">
                          <span>Ethical compliance check</span>
                          <span>90%</span>
                        </div>
                        <Progress value={90} />
                      </div>
                    </div>
                  )}

                  {impactData && !isAnalyzing && (
                    <div className="space-y-4 p-4 border rounded-lg bg-muted/20">
                      <div className="flex items-center justify-between">
                        <h3 className="text-lg font-semibold">{impactData.name}</h3>
                        <div className="flex items-center gap-2">
                          <Badge className={`${getSustainabilityColor(impactData.sustainabilityRating)} text-white`}>
                            Sustainability: {impactData.sustainabilityRating}
                          </Badge>
                          {blockchainVerified && (
                            <Badge variant="outline" className="text-green-600">
                              <Award className="h-3 w-3 mr-1" />
                              Verified
                            </Badge>
                          )}
                        </div>
                      </div>

                      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                        <div className="text-center">
                          <div className="flex items-center justify-center mb-1">
                            <Leaf className="h-5 w-5 text-green-500" />
                          </div>
                          <p className="text-2xl font-bold text-green-600">
                            {Math.abs(impactData.carbonFootprint)}
                          </p>
                          <p className="text-xs text-muted-foreground">tons CO₂ saved</p>
                        </div>
                        <div className="text-center">
                          <div className="flex items-center justify-center mb-1">
                            <Users className="h-5 w-5 text-blue-500" />
                          </div>
                          <p className="text-2xl font-bold text-blue-600">
                            {impactData.usersImpacted.toLocaleString()}
                          </p>
                          <p className="text-xs text-muted-foreground">users impacted</p>
                        </div>
                        <div className="text-center">
                          <div className="flex items-center justify-center mb-1">
                            <Shield className="h-5 w-5 text-purple-500" />
                          </div>
                          <p className="text-2xl font-bold text-purple-600">
                            {impactData.ethicalScore}%
                          </p>
                          <p className="text-xs text-muted-foreground">ethical score</p>
                        </div>
                        <div className="text-center">
                          <div className="flex items-center justify-center mb-1">
                            <Target className="h-5 w-5 text-orange-500" />
                          </div>
                          <p className="text-2xl font-bold text-orange-600">
                            {impactData.sdgAlignment.length}
                          </p>
                          <p className="text-xs text-muted-foreground">SDGs aligned</p>
                        </div>
                      </div>

                      <div>
                        <p className="text-sm font-medium mb-2">Impact Areas</p>
                        <div className="flex flex-wrap gap-2">
                          {impactData.impactAreas.map(area => (
                            <Badge key={area} variant="secondary">{area}</Badge>
                          ))}
                        </div>
                      </div>
                    </div>
                  )}
                </CardContent>
              </Card>
            </TabsContent>

            <TabsContent value="sdg" className="space-y-4">
              <Card>
                <CardHeader>
                  <CardTitle>UN Sustainable Development Goals Alignment</CardTitle>
                  <CardDescription>
                    Track your project's contribution to global sustainability goals
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    {SDG_GOALS.map(goal => (
                      <div key={goal.id} className="p-4 border rounded-lg hover:shadow-md transition-shadow">
                        <div className="flex items-start gap-3">
                          <div className={`w-12 h-12 ${goal.color} rounded-lg flex items-center justify-center text-white text-xl`}>
                            {goal.icon}
                          </div>
                          <div className="flex-1">
                            <h4 className="font-medium mb-1">SDG {goal.id}: {goal.title}</h4>
                            <p className="text-xs text-muted-foreground mb-3">{goal.description}</p>
                            
                            <div className="space-y-2">
                              <div className="flex justify-between text-sm">
                                <span>Global Progress</span>
                                <span>{goal.progress}%</span>
                              </div>
                              <Progress value={goal.progress} className="h-2" />
                              
                              <div className="flex justify-between text-sm">
                                <span>Project Relevance</span>
                                <span>{goal.relevance}%</span>
                              </div>
                              <Progress value={goal.relevance} className="h-2" />
                            </div>
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>
                </CardContent>
              </Card>
            </TabsContent>

            <TabsContent value="ethics" className="space-y-4">
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <Shield className="h-5 w-5" />
                    AI Ethics & Compliance
                  </CardTitle>
                  <CardDescription>
                    Automated assessment of ethical AI practices and compliance
                  </CardDescription>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div className="space-y-4">
                      <div className="p-4 border rounded-lg">
                        <h4 className="font-medium mb-2 flex items-center gap-2">
                          <div className="w-3 h-3 bg-green-500 rounded-full"></div>
                          Data Privacy
                        </h4>
                        <p className="text-sm text-muted-foreground mb-2">
                          GDPR and privacy compliance assessment
                        </p>
                        <Progress value={95} className="h-2" />
                        <p className="text-xs text-green-600 mt-1">Excellent compliance</p>
                      </div>

                      <div className="p-4 border rounded-lg">
                        <h4 className="font-medium mb-2 flex items-center gap-2">
                          <div className="w-3 h-3 bg-green-500 rounded-full"></div>
                          Algorithmic Fairness
                        </h4>
                        <p className="text-sm text-muted-foreground mb-2">
                          Bias detection and fairness metrics
                        </p>
                        <Progress value={88} className="h-2" />
                        <p className="text-xs text-green-600 mt-1">Good fairness score</p>
                      </div>

                      <div className="p-4 border rounded-lg">
                        <h4 className="font-medium mb-2 flex items-center gap-2">
                          <div className="w-3 h-3 bg-yellow-500 rounded-full"></div>
                          Transparency
                        </h4>
                        <p className="text-sm text-muted-foreground mb-2">
                          Model explainability and documentation
                        </p>
                        <Progress value={72} className="h-2" />
                        <p className="text-xs text-yellow-600 mt-1">Needs improvement</p>
                      </div>
                    </div>

                    <div className="space-y-4">
                      <div className="p-4 border rounded-lg">
                        <h4 className="font-medium mb-2 flex items-center gap-2">
                          <div className="w-3 h-3 bg-green-500 rounded-full"></div>
                          Security
                        </h4>
                        <p className="text-sm text-muted-foreground mb-2">
                          Data security and protection measures
                        </p>
                        <Progress value={92} className="h-2" />
                        <p className="text-xs text-green-600 mt-1">Strong security</p>
                      </div>

                      <div className="p-4 border rounded-lg">
                        <h4 className="font-medium mb-2 flex items-center gap-2">
                          <div className="w-3 h-3 bg-green-500 rounded-full"></div>
                          Accountability
                        </h4>
                        <p className="text-sm text-muted-foreground mb-2">
                          Clear responsibility and governance
                        </p>
                        <Progress value={85} className="h-2" />
                        <p className="text-xs text-green-600 mt-1">Well defined</p>
                      </div>

                      <div className="p-4 border rounded-lg">
                        <h4 className="font-medium mb-2 flex items-center gap-2">
                          <div className="w-3 h-3 bg-blue-500 rounded-full"></div>
                          Human Oversight
                        </h4>
                        <p className="text-sm text-muted-foreground mb-2">
                          Human-in-the-loop mechanisms
                        </p>
                        <Progress value={78} className="h-2" />
                        <p className="text-xs text-blue-600 mt-1">Adequate oversight</p>
                      </div>
                    </div>
                  </div>

                  <div className="p-4 bg-green-50 dark:bg-green-950 rounded-lg border border-green-200 dark:border-green-800">
                    <div className="flex items-center gap-2 mb-2">
                      <Award className="h-5 w-5 text-green-600" />
                      <h4 className="font-medium text-green-700 dark:text-green-300">
                        Ethics Certification Ready
                      </h4>
                    </div>
                    <p className="text-sm text-green-600 dark:text-green-400">
                      Your project meets the requirements for AI ethics certification. 
                      Overall compliance score: 95%
                    </p>
                  </div>
                </CardContent>
              </Card>
            </TabsContent>
          </Tabs>
        </div>
      </div>
    </div>
  );
}